LID=[0]
LName=[Dead]
LHello=[Вы погибли…]
LVar=[]
\Quest
QID=[0]
QCheck=[]
QText=[Чтож. Поздравляю, ваш скелет будет кому-то красивым украшением) ]
QEffect=[P.Dead()]
QVar=[]
\qa [1] 	qatext=[Нееет]
qacheck=[] 	qn=[1.0]
\Quest
QID=[1]
QCheck=[]
QText=[Черти решили ещё немного над вами поржать и дают ещё один шанс. Повеселите их)]
QEffect=[Reset()]
QVar=[]
\qa [1] 	qatext=[Ура]
qacheck=[] 	qn=[1-0]
Это другой файл.